### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by ktagu9987** [catfoolyou/EaglerX-Server#1]
i dont know why but when i try to run command from terminal it says command not found

**Comment by catfoolyou** [comment]
Which one? Did you follow the steps exactly as listed?

**Comment by ktagu9987** [comment]
Yes

**Comment by ktagu9987** [comment]
I already try to fork and open in girpod and it didn’t work

**Comment by ktagu9987** [comment]
It mean gitpod

**Comment by catfoolyou** [comment]
What does it say? Send a screenshot or somethin

**Comment by kosei9987a** [comment]
im back with sub account






here is log:
[01:35:44] [main/INFO]: Using mbed TLS based native cipher.
[01:35:44] [main/INFO]: Using zlib based native compressor.
[01:35:44] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543
[01:35:44] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[01:35:44] [main/INFO]: Epoll is working, utilising it!
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[01:35:44] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:44] [main/WARN]: :>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>      EAGLERCRAFTXBUNGEE WARNING:
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>  This plugin wasn't tested to be 'working'
[01:35:44] [main/WARN]: :>  with ANY version of BungeeCord (and forks)
[01:35:44] [main/WARN]: :>  apart from the versions listed below:
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>  - BungeeCord: 1.20-R0.2-SNAPSHOT:231024b:1777
[01:35:44] [main/WARN]: :>  - Waterfall: 1.20-R0.2-SNAPSHOT:d85fe36:556
[01:35:44] [main/WARN]: :>  - FlameCord: 1.1.1
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>  This is not a Bukkit/Spigot plugin!
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>  Use "-Deaglerxbungee.stfu=true" to hide
[01:35:44] [main/WARN]: :>  
[01:35:44] [main/WARN]: :>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>
[01:35:44] [main/INFO] [EaglercraftXBungee]: Loading vanilla profile: lax1dude
[01:35:49] [main/WARN] [EaglercraftXBungee]: Profile load timed out
[01:35:49] [main/INFO]: Loaded plugin EaglercraftXBungee version 1.0.9 by lax1dude
[01:35:49] [main/WARN]: Forced host server pvp is not defined
[01:35:49] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:a5bbdbe:543 by WaterfallMC
[01:35:49] [main/ERROR] [EaglercraftXBungee]: Online mode is set to false! Authentication system has been disabled
[01:35:49] [Netty Worker IO Thread #0/INFO] [EaglercraftXBungee]: Eaglercraft is listening on: /0.0.0.0:8081
[01:35:49] [main/INFO] [EaglercraftXBungee]: Connected to database: jdbc:sqlite:eaglercraft_skins_cache.db
[01:35:49] [main/INFO]: Enabled plugin EaglercraftXBungee version 1.0.9 by lax1dude
[01:35:49] [Netty Boss IO Thread #0/INFO]: Listening on /127.0.0.1:25577
[01:35:49] [Skin Download Thread #0/ERROR] [EaglercraftXBungee]: Exception loading vanilla default profile!
java.io.IOException: Connection failed
	at net.lax1dude.eaglercraft.v1_8.plugin.gateway_bungeecord.skins.BinaryHttpClient$NettyHttpChannelFutureListener.operationComplete(BinaryHttpClient.java:103) ~[?:?]
	at net.lax1dude.eaglercraft.v1_8.plugin.gateway_bungeecord.skins.BinaryHttpClient$NettyHttpChannelFutureListener.operationComplete(BinaryHttpClient.java:1) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:614) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungee.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
[01:35:59] [main/INFO]: Command not found

**Comment by kosei9987a** [comment]
![image](https://github.com/catfoolyou/EaglerX-Server/assets/158532997/243b77d6-f2f7-48b6-a01d-54ffa643e516)

**Comment by kosei9987a** [comment]
taht what it shows

**Comment by catfoolyou** [comment]
What does it show in the ports tab?
If the port is there set it to public and click the link

**Comment by kosei9987a** [comment]
it didnt work in bungee 1.08 so i update itto 1.0.9 and then it didnt work

**Comment by kosei9987a** [comment]
![image](https://github.com/catfoolyou/EaglerX-Server/assets/158532997/a3a0149f-23d1-4be6-8526-87d0903f244f)

**Comment by catfoolyou** [comment]
Click on the 8081 pork and use the wss link

**Comment by ktagu9987** [comment]
dont work and the even the plugin is cant 
loded

**Comment by catfoolyou** [comment]
What happens when you click on the link for 8081? What does the page look like? Screenshot please.

**Comment by kosei9987a** [comment]
![image](https://github.com/catfoolyou/EaglerX-Server/assets/158532997/86d7a0a5-5ebc-4c94-b7fe-58985a1a2977)

**Comment by kosei9987a** [comment]
https://congenial-umbrella-4jjxw6gv447vf7vj4.github.dev/

**Comment by kosei9987a** [comment]
here is my codespace

**Comment by catfoolyou** [comment]
It literally gives you a link.

**Comment by kosei9987aaa** [comment]
hi im back i can go in to eaglercraft,but the command dont work nither shell or eaglercraft command.
im still stuck on same problem

**Comment by catfoolyou** [comment]
Use the link that it gives you on the websocket upgrade failure screen

**Comment by kosei9987aaa** [comment]
i want use command like /gamemode, /give

> Use the link that it gives you on the websocket upgrade failure screen

that doesnt work

**Comment by catfoolyou** [comment]
Dude, just forget about it. Use Ayun's replit instead. I will not give you any links, find it yourself
